s3_base: &s3_base
  service: S3
  access_key_id: <%= GlobalConfig.get("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= GlobalConfig.get("AWS_SECRET_ACCESS_KEY") %>
  region: us-east-1
  bucket: <%= PUBLIC_STORAGE_S3_BUCKET %>
  public: true

test:
  <<: *s3_base
  endpoint: <%= GlobalConfig.get("AWS_S3_ENDPOINT") %>
  force_path_style: true
  access_key_id: minioadmin
  secret_access_key: minioadmin

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  <<: *s3_base
